### ISSUE TITLE
Real Play Store crashes after installation

### ISSUE THREAD

**Issue by Freepony** [nift4/microg_installer_revived#107]
I have put Phonesky.apk into `/data/adb` as instructed and flashed zip with Magisk. The real Play Store has been installed successfully. I gave all permissions but it wouldn't launch. I also checked microG services permissions, logged into my Google account, cleared app data and cache, wiped system cache and dalvik. I tried 4 different versions of Play Store (not modified from apkmirror) but none of them worked.
At the same time microg-gapps module works fine.
Am I missing something?

OS: ArrowOS 12.1
Here are the logs:

```
FATAL EXCEPTION: main
Process: com.android.vending, PID: 7046
java.lang.RuntimeException: Unable to create application com.google.android.finsky.application.classic.ClassicApplication: java.lang.IllegalStateException: Failed to initialize FinskyApp
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6767)
 at android.app.ActivityThread.access$1500(ActivityThread.java:256)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7870)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalStateException: Failed to initialize FinskyApp
 at jqd.az(PG:15)
 at jsm.i(PG:567)
 at jsm.onCreate(PG:16)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1226)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6762)
 ... 9 more
Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: Calling identity is not authorized
 at aohd.r(PG:21)
 at aohd.get(PG:10)
 at nj.e(PG:2)
 at jqd.az(PG:6)
 ... 13 more
Caused by: java.lang.SecurityException: Calling identity is not authorized
 at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
 at android.os.Parcel.createException(Parcel.java:2410)
 at android.os.Parcel.readException(Parcel.java:2393)
 at android.os.Parcel.readException(Parcel.java:2335)
 at android.app.admin.IDevicePolicyManager$Stub$Proxy.getDeviceOwnerComponent(IDevicePolicyManager.java:9171)
 at android.app.admin.DevicePolicyManager.getDeviceOwnerComponentInner(DevicePolicyManager.java:7956)
 at android.app.admin.DevicePolicyManager.getDeviceOwnerComponentOnAnyUser(DevicePolicyManager.java:7939)
 at jqd.W(PG:84)
 at jrl.b(PG:17)
 at avrg.a(PG:6)
 at aohf.e(PG:3)
 at aohh.run(PG:42)
 at asla.run(PG:8)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at njj.run(PG:131)
 at java.lang.Thread.run(Thread.java:920)
```

**Comment by nift4** [comment]
clean install?

**Comment by Freepony** [comment]
Yes. Before each attempt, I deleted Magisk module itself, `com.android.vending` and `com.google.android.gms`. There were no remains of MicroG in `/data/adb/modules` and `/system/priv-app`.
I tried to return to [Psk-Ita MicroG](https://github.com/Psk-Ita/microG-GApps) after all this. Their Play Store works fine.

**Comment by nift4** [comment]
you can try to download & use that play store apk, and if that doesn't help please create a bugreport in developer settings and email it to me nift4@protonmail.com

**Comment by nift4** [comment]
stale
