### ISSUE TITLE
342 b0rked on clean install

### ISSUE THREAD

**Issue by pwn0r** [nift4/microg_installer_revived#114]
I had this version on other devices (I use microg on every one of them, no gapps). But there it was an update from 341 to 342. 
I dont use magisk, only KSU now. But it did work correctly after update (341 -> 342) on my other devices.

One device was wiped and clean installed (upgraded from A13 to A14), with native KSU support. Installed microg-revived, 342 version, after reboot crashes and all permissions are clearly b0rked.

`time: 1706376419174
msg: java.lang.SecurityException: Not allowed to access cell info
stacktrace: java.lang.SecurityException: Not allowed to access cell info
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3045)
	at android.os.Parcel.readException(Parcel.java:3028)
	at android.os.Parcel.readException(Parcel.java:2970)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.requestCellInfoUpdate(ITelephony.java:9641)
	at android.telephony.TelephonyManager.requestCellInfoUpdate(TelephonyManager.java:6794)
	at org.microg.gms.location.network.cell.CellDetailsSource.startScan(CellDetailsSource.kt:24)
	at org.microg.gms.location.network.NetworkLocationService.scan(NetworkLocationService.kt:113)
	at org.microg.gms.location.network.NetworkLocationService.highPowerScanRunnable$lambda$0(NetworkLocationService.kt:52)
	at org.microg.gms.location.network.NetworkLocationService.$r8$lambda$SLw0bsuDr5M3d2uTMZYf0gbGqTc(Unknown Source:0)
	at org.microg.gms.location.network.NetworkLocationService$$ExternalSyntheticLambda3.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)`

The microg fails to register itself as a location provider. In fact most permissions are missing, like all location-based ones, sms and phone. You can manually add these permissions, and then suddenly microg actually understands it is a location provider. Still, background location and sms remain missing and impossible to add even manually. Also location does not work.  Phone restarts, reinstalling same module etc does not help the issue.

The issue was solved by removing 342 from ksu manager and installing 341 instead.

**Comment by nift4** [comment]
Download and install https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/microG/microG.apk to solve the issue that you are unable to grant background location or SMS. After that, make sure to grant all permissions.

For further root cause debugging, please submit module installation log.

**Comment by nift4** [comment]
Stale.
