### ISSUE TITLE
Error: androidx.multidex.MultiDexApplication

### ISSUE THREAD

**Issue by thunder11** [nift4/microg_installer_revived#128]
With the latest MicroG after install in Magisk and reboot, I get crash report : 

time: 1711387991107
device fp:OnePlus/Nord/Nord:12/RKQ1.211119.001/Q.202212051830:user/release-keys
product board:lito
superior vers:SuperiorOS-Fourteen-avicii-RELEASE-20240210-1130
msg: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f140003
stacktrace: java.lang.RuntimeException: Unable to instantiate application androidx.multidex.MultiDexApplication package com.google.android.gms: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f140003
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1475)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1404)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7010)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8240)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:554)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f140003
	at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:297)
	at android.content.res.Resources.getResourceEntryName(Resources.java:2379)
	at android.security.net.config.XmlConfigSource.ensureInitialized(XmlConfigSource.java:89)
	at android.security.net.config.XmlConfigSource.getPerDomainConfigs(XmlConfigSource.java:55)
	at android.security.net.config.ManifestConfigSource.getPerDomainConfigs(ManifestConfigSource.java:45)
	at android.security.net.config.ApplicationConfig.ensureInitialized(ApplicationConfig.java:175)
	at android.security.net.config.ApplicationConfig.isCleartextTrafficPermitted(ApplicationConfig.java:130)
	at android.security.net.config.NetworkSecurityConfigProvider.handleNewApplication(NetworkSecurityConfigProvider.java:60)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1466)

Thanks

**Comment by nift4** [comment]
Do you use any one of Magisk Hide, Denylist, SuList (with microG hidden respectively) or Universal SafetyNetFix or PlayIntegrityFix or related forks or Shamiko?

**Comment by thunder11** [comment]
No, at the time i had no such modules installed. Today I tried shimiko and Playintegrity didnt work so I disabled it.

**Comment by nift4** [comment]
What modules do you use? What about DenyList, SuList, Magisk Hide? Are you using official Magisk? Do you use KernelSU with Magisk?

**Comment by thunder11** [comment]
Hi, 
At this time my active modules are:
De-bloater, MicroG Installer Revived 3.4.2-0,systemless hosts, zygisk-LSposed. 
In settings : zygisk is enabled, enforce denylist os magisk is official build

**Comment by nift4** [comment]
Why are you using Debloater? does the ROM ship with Gapps?

**Comment by thunder11** [comment]
No, its vanilla ROM (Superior OS), and I install De-bloater as part of a routine. Do you think I should remove all the modules and then try to Update MicroG in Magisk?
Thank you very much for all your help and work you put into this project

**Comment by nift4** [comment]
I'm not sure what exactly the debloater does, hence it may help if you disable/remove it for testing.

**Comment by linux-leo** [comment]
I am getting the same error, my microg installation is completely fucked and I cant even access the settings. That shortcut is broken too. Also running debloater, but that should be unrelated imo.

**Comment by thunder11** [comment]
Its not, I removed De-Bloater, disabled all modules in Magisk and still have the same error.

**Comment by nift4** [comment]
Can you try to [download](https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/microG/microG.apk) & install this (unmodified microG) APK?

**Comment by linux-leo** [comment]
Works fine with the apk installed on top.

**Comment by thunder11** [comment]
I removed MicroG module and installed proposed apk and it worked. However I had to install fakegapps lsposed module to make Signature Spoofing work.

**Comment by nift4** [comment]
You were not supposed to remove the module. Most apps don't work if microG is not a system app.
As the workaround seems to work, I'm closing this.
