### ISSUE TITLE
Attempt to invoke virtual method getConfiguration() on a null object reference

### ISSUE THREAD

**Issue by Bruno-FGM** [nift4/microg_installer_revived#129]
Hello, I have repeated errors since upgraded to latest Microg Revived version 3.4.3 (from Magisk version 27.0)
Had no trouble with previous one... 

SDK: 34
PRODUCT_NAME: hero2ltexx
DEVICE_NAME: hero2ltexx
BOARD_NAME: universal8890
SUPPORTED_ABIS: arm64-v8a, armeabi-v7a, armeabi
MANUFACTURER: samsung
BRAND: samsung
MODEL: SM-G935F

FATAL EXCEPTION: main
Process: com.google.android.gms, PID: 13520
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:266)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6939)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by Bruno-FGM** [comment]
After installing again manually as per documentation, all is good. 
Sorry not to check properly before logging the issue...
