### ISSUE TITLE
MicroG Services keeps crashing, manually install apk is not successful

### ISSUE THREAD

**Issue by morturio** [nift4/microg_installer_revived#136]
hi,

after updated magisk to 27.0 (27000) AND microg to 3.4.3-0 MicroG Services keeps crashing. i think its the common issue but when i try to install the apk manually i get an error, that the app was not installed ;S

any suggestions?

`type: crash
osVersion: Xiaomi/santoni/santoni:7.1.2/N2G47H/V9.5.10.0.NAMMIFD:user/release-keys
package: com.google.android.gms:240913002
process: com.google.android.gms
processUptime: 28 + 453 ms
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
 at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:268)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
 at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2140)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7938)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)`

**Comment by nift4** [comment]
can you try to install the apk with adb to find the cause of "Not installed" error?

**Comment by morturio** [comment]
Hi,

installation via adb works. microg does not crash anymore. I should have tried adb install before ;S

thank you very much
