### ISSUE TITLE
3440: GmsCore.apk ENOENT

### ISSUE THREAD

**Issue by bphd** [nift4/microg_installer_revived#154]
Error: Unable to open file: /data/adb/modules_update/microg_installer/system/priv-app/GmsCore/GmsCore.apk

Consider using a file under /data/local/tmp/

Error: Can't open file: /data/adb/modules_update/microg_installer/system/priv-app/GmsCore/GmsCore.apk

Exception occurred while executing 'install':

java.lang.IllegalArgumentException: Error: Can't open file: /data/adb/modules_update/microg_installer/system/priv-app/GmsCore/GmsCore.apk

at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:688)

at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1557)

at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1523)

at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:236)

at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)

at android.os.ShellCommand.exec(ShellCommand.java:38)

at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6455)

at android.os.Binder.shellCommand(Binder.java:1097)

at android.os.Binder.onTransact(Binder.java:914)

at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4403)

at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6439)

at android.os.Binder.execTransactInternal(Binder.java:1363)

at android.os.Binder.execTransact(Binder.java:1304)

**Comment by nift4** [comment]
insufficient description, sorry. i need more details if you still have this issue

**Comment by bphd** [comment]
@nift4 That's all logs available, need to fix

**Comment by nift4** [comment]
You could describe what you did so far, what device this is, what Android version this is, if you are running a custom ROM, if you are rooted, if you are trying to install ReVanced, if you had any other issues and if you solved them, if it worked before and this is an update and many more things...

**Comment by bphd** [comment]
Pretty much same as other issue

**Comment by nift4** [comment]
Did you just install the unmodified(!) ZIP and this error came up?

**Comment by bphd** [comment]
It happens upon installation iirc. The file was the original one afaik

**Comment by nift4** [comment]
well it shouldnt impact you

**Comment by bphd** [comment]
The installation fails subsequestially

**Comment by nift4** [comment]
I just realized why this happens, stupid mistake, thanks for the report

**Comment by bphd** [comment]
No problem, don't forget to link the PR/commit to that issue so it would be resolved by a push rather than a manual closing and the user won't feel played

**Comment by nift4** [comment]
b54f5b387f85537b4588d9ad1df51bd4745b5fd2
