### ISSUE TITLE
Google Lens

### ISSUE THREAD

**Issue by bphd** [nift4/microg_installer_revived#155]
How

Because app.revanced.android.gms is supposed to replace com.google.android.googlequicksearchbox

**Comment by nift4** [comment]
insufficient description, sorry. i need more details if you still have this issue

**Comment by bphd** [comment]
@nift4 It doesn't open

**Comment by nift4** [comment]
You could describe what you did so far, what device this is, what Android version this is, if you are running a custom ROM, if you are rooted, if you are trying to install ReVanced, if you had any other issues and if you solved them, if it worked before and this is an update and many more things...

**Comment by nift4** [comment]
1. why did you say "app.revanced.android.gms", if you use ReVanced microG you are in the wrong issue tracker
2. "is supposed to replace com.google.android.googlequicksearchbox" well idk about ReVanced microG but normal microG doesn't
3. Google Lens, by opening the Google app and pressing the cam button, works here. If it doesn't open for you I'll need more details (logs!) and a description what happens on screen ("I pressed the camera button and it said Google was stopped" or something like that)

**Comment by bphd** [comment]
No, I use MGIV but I use RV to patch some apps

If it doesn't replace it, how will it work?

I press the Google Lens app icon directly

Iirc it showed rapidly a black screen and was returning to launcher

**Comment by nift4** [comment]
Try doing what I explained to you re opening the app

**Comment by bphd** [comment]
What explanation?

**Comment by nift4** [comment]
"opening the Google app and pressing the cam button"

**Comment by nift4** [comment]
I don't understand how camera app is related to this. My camera app has no Google Lens integration either. I am asking you to open the Google app and press the colored camera icon inside the huge search bar, that directly opens Lens for me without having the Lens app installed. (Because Lens initially was an app, but they're moving people to the Google app version.)

**Comment by nift4** [comment]
https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox

**Comment by bphd** [comment]
Isn't that application bogus and MGIV supposed to replace it with something more respective of the user?

**Comment by nift4** [comment]
You want to use Google Lens, you need Google app. There is no replacement for this app, only for Play Store and for Play Services.

**Comment by bphd** [comment]
time: 1725548826858
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference
stacktrace: java.lang.RuntimeException: Unable to instantiate application androidx.multidex.MultiDexApplication package com.google.android.gms: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1475)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1404)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7021)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8246)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference
	at android.app.LoadedApk.getAssets(LoadedApk.java:1362)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1452)
	... 11 more

**Comment by nift4** [comment]
This is caused by applying root hiding (Magisk Hide, DenyList, SafetyNet fix / Play Integrity fix and many other things) to microG / Play Store. It creates a chicken egg problem: APK is added by Magisk, but microG / Play Store can't see Magisk changes => microG / Play Store can't see it's own APK. The easiest fix is to install the apk as user apk in addition, and system will see apk on partition and is happy and microG / Play Store won't crash because it has userdata APK.

**Comment by nift4** [comment]
You didn't tell me what was crashing, how would I know?? The crashing one. (It's also mentioned in the README by the way.)

**Comment by bphd** [comment]
It tries to update the application to the same version, exits directly without trying to update and the application continues to crash. Maybe it was already installed?

**Comment by nift4** [comment]
That seems to be a rom bug. To find out if it supports spoofing without looking at code, ask the maintainers.

**Comment by bphd** [comment]
Isn't it weird that it tries to update at same version? Maybe it's already installed

**Comment by nift4** [comment]
Nope it's not weird, it's normal to be able to install the same version again and that's also what I asked you to do.

**Comment by bphd** [comment]
Upon deactivation of all KSU/LSP modules related to Google, microG stops to loop crash and keyboard is available, but trying to install the APK is pretty much the same experience at the difference that now it tries to downgrade instead or same version (from 23.... to 0.0.....) I guess that it tries to replace something official because there is no systemless anymore

time: 1725553330240
msg: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
stacktrace: java.lang.RuntimeException: Unable to start receiver com.android.packageinstaller.InstallEventReceiver: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4499)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8246)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:1127)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1103)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:436)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:436)
	at com.android.packageinstaller.EventResultPersister.onEventReceived(EventResultPersister.java:189)
	at com.android.packageinstaller.InstallEventReceiver.onReceive(InstallEventReceiver.java:50)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4490)
	... 9 more

**Comment by nift4** [comment]
You didn't disable root hiding, you said you disabled all modules. That's not the same thing

**Comment by bphd** [comment]
Collecting information about com.google.android.gms
Checking if com.google.android.gms is installed
Collecting file path of com.google.android.gms
Checking if file path of com.google.android.gms is on /data
- ERROR: expected microG install path to be on /data, but it's /system/priv-app/microG/microG.apk
- Error: Failed to install module script
Error: Failed to install module script

**Comment by bphd** [comment]
> You didn't disable root hiding, you said you disabled all modules. That's not the same thing

You mean "Upon deactivation of all KSU/LSP modules related to Google"?

**Comment by nift4** [comment]
> ERROR: expected microG install path to be on /data, but it's /system/priv-app/microG/microG.apk

make sure you have microG as user app (eg with `adb install`), that's the entire point of that check

> You mean "Upon deactivation of all KSU/LSP modules related to Google"?

Yes. I was talking about keeping microG Installer and FakeGApps enabled and disabling: Universal SafetyNet Fix, Shamiko, Play Integrity Fix, Magisk Hide/DenyList for microG related apps, enabling(!) KSU mount modules for microG related apps

**Comment by bphd** [comment]
> > ERROR: expected microG install path to be on /data, but it's /system/priv-app/microG/microG.apk
> 
> make sure you have microG as user app (eg with `adb install`), that's the entire point of that check
> 
> > You mean "Upon deactivation of all KSU/LSP modules related to Google"?
> 
> Yes. I was talking about keeping microG Installer and FakeGApps enabled and disabling: Universal SafetyNet Fix, Shamiko, Play Integrity Fix, Magisk Hide/DenyList for microG related apps, enabling(!) KSU mount modules for microG related apps

$ adb install storage/downloads/microG.apk
* daemon not running; starting now at tcp:5037
* daemon started successfully
adb: no devices/emulators found

So if I get it right, only MGIR and FGA modules activated and whatever app KSU mounted I want but in addition

**Comment by nift4** [comment]
> adb: no devices/emulators found

make sure to plug in your device, if on windows with proper drivers; and grant the request; but how to get that working is not really related to microg_installer_revived anymore

> -12: Integrity APl error (-12): Unknown
> internal Google server error.
> Retry with an exponential backoff.

Play Integrity is (currently?) not supported. It may work but I don't know how to get it to work and can't help with it.

**Comment by bphd** [comment]
> > adb: no devices/emulators found
> 
> make sure to plug in your device, if on windows with proper drivers; and grant the request; but how to get that working is not really related to microg_installer_revived anymore
> 
> > -12: Integrity APl error (-12): Unknown
> > internal Google server error.
> > Retry with an exponential backoff.
> 
> Play Integrity is (currently?) not supported. It may work but I don't know how to get it to work and can't help with it.

How to plug my device into my device? It's nonsensical. Not on Windows but Android

I'm currently trying to get Google services to get integrity. Because I seem to understand that naturally Google don't grant integrity if no Google services are available. I installed and activated what you said and still haven't integrity

**Comment by nift4** [comment]
> How to plug my device into my device? It's nonsensical. Not on Windows but Android

...in that case, use `su`, then `cp storage/downloads/microG.apk /data/local/tmp/microG.apk && pm install /data/local/tmp/microG.apk`

> I'm currently trying to get Google services to get integrity

If you want integrity you need to use real Google services as far as I know. Atleast real Play Store, but as I said, I don't really know.

**Comment by bphd** [comment]
I have real Play Store, I just don't do anything with it lol

So, I installed as user app and updated, but nothing new really. It was already detecting spoofing since FGA, and integrity is still not on. Soooo, I don't really know how to check if I resolved the problem, to check if MGIR is fully operational now, like, more operational than before that problem

**Comment by bphd** [comment]
ReVanced stuff is basically normal apps but patched. ReVanced GMS is archived do I don't really know how it's managed now

But ReVanced stuff is only YTB/M, not everything else

**Comment by bphd** [comment]
time: 1725897055910
msg: java.lang.NumberFormatException: For input string: "IntegrityService "
stacktrace: java.lang.NumberFormatException: For input string: "IntegrityService "
	at java.lang.Integer.parseInt(Integer.java:790)
	at java.lang.Integer.parseInt(Integer.java:908)
	at h2.b.a(SourceFile:30)
	at androidx.appcompat.widget.j.a(SourceFile:31)
	at androidx.appcompat.widget.j.run(SourceFile:12)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8594)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by bphd** [comment]
time: 1725907209922
msg: java.lang.SecurityException: You either need MANAGE_USERS or CREATE_USERS permission to: query users
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.vending/com.google.android.finsky.activities.MainActivity}: java.lang.SecurityException: You either need MANAGE_USERS or CREATE_USERS permission to: query users
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3993)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8594)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.SecurityException: You either need MANAGE_USERS or CREATE_USERS permission to: query users
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3187)
	at android.os.Parcel.createException(Parcel.java:3171)
	at android.os.Parcel.readException(Parcel.java:3154)
	at android.os.Parcel.readException(Parcel.java:3096)
	at android.os.IUserManager$Stub$Proxy.getUsers(IUserManager.java:2335)
	at android.os.UserManager.getUsers(UserManager.java:4877)
	at android.os.UserManager.getUsers(UserManager.java:4818)
	at android.os.UserManager.getUserCount(UserManager.java:4791)
	at ablq.aL(PG:13)
	at nvy.a(PG:103)
	at kwh.<init>(PG:13)
	at lrs.a(PG:207)
	at zmu.apply(PG:161)
	at j$.util.Map$-CC.$default$computeIfAbsent(SourceFile:10)
	at j$.util.Map$-EL.computeIfAbsent(Unknown Source:22)
	at afdq.C(PG:18)
	at afdq.B(PG:13)
	at kwe.a(PG:3)
	at nvs.a(PG:11)
	at nvs.i(PG:1)
	at nvs.h(PG:2)
	at kwl.Y(PG:24)
	at kwl.K(PG:2)
	at aexh.U(PG:321)
	at www.<init>(PG:9)
	at wwh.T(PG:1528)
	at zzzi.onCreate(PG:197)
	at kpt.onCreate(PG:1)
	at android.app.Activity.performCreate(Activity.java:8978)
	at android.app.Activity.performCreate(Activity.java:8956)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1532)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3975)
	... 13 more

**Comment by bphd** [comment]
time: 1725959831649
msg: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802 SQLITE_IOERR_FSTAT)
stacktrace: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802 SQLITE_IOERR_FSTAT)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:786)
	at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:678)
	at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:110)
	at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:1043)
	at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:1031)
	at android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:1342)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:388)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
	at org.microg.gms.nearby.exposurenotification.ExposureDatabase.isEmpty(ExposureDatabase.kt:744)
	at org.microg.gms.nearby.exposurenotification.ui.ExposureNotificationsSettingsProvider$getEntriesDynamic$2.invokeSuspend(ExposureNotificationsSettingsProvider.kt:34)
	at org.microg.gms.nearby.exposurenotification.ui.ExposureNotificationsSettingsProvider$getEntriesDynamic$2.invoke(Unknown Source:8)
	at org.microg.gms.nearby.exposurenotification.ui.ExposureNotificationsSettingsProvider$getEntriesDynamic$2.invoke(Unknown Source:4)
	at org.microg.gms.nearby.exposurenotification.ExposureDatabase$Companion$with$2.invokeSuspend(ExposureDatabase.kt:1056)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d7c7850, Dispatchers.Main.immediate]

**Comment by bphd** [comment]
Long story short, to get everything working it's better to have quicksearchbox vending gsf gms, and at least basic integrity if not device integrity. Not so much to get certificaiton but because it's a proof that everything is configured fine on Google side. And you need things installed right, meaning systemized with MGIR
