### ISSUE TITLE
Play Store constant crashes, missing CREATE_USERS or MANAGE_USERS

### ISSUE THREAD

**Issue by ParzivalWolfram** [nift4/microg_installer_revived#185]
LogFox reports 3 or 4 crashes per second (making my device slow to a crawl) for the Play Store, with the following log:

```
FATAL EXCEPTION: main
Process: com.android.vending, PID: 9447
java.lang.SecurityException: You either need MANAGE_USERS or CREATE_USERS permission to: query users
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.os.IUserManager$Stub$Proxy.getUsers(IUserManager.java:1973)
	at android.os.UserManager.getUsers(UserManager.java:3213)
	at android.os.UserManager.getUsers(UserManager.java:3200)
	at android.os.UserManager.getUsers(UserManager.java:3186)
	at android.os.UserManager.getUserCount(UserManager.java:3172)
	at achq.aM(PG:13)
	at ogl.a(PG:103)
	at lfg.<init>(PG:13)
	at mbd.a(PG:208)
	at aafg.apply(PG:161)
	at j$.util.Map$-CC.$default$computeIfAbsent(SourceFile:10)
	at j$.util.Map$-EL.computeIfAbsent(Unknown Source:22)
	at agcu.B(PG:18)
	at agcu.A(PG:13)
	at lfd.a(PG:3)
	at oge.a(PG:11)
	at oge.i(PG:1)
	at oge.h(PG:2)
	at lfj.Y(PG:24)
	at lfj.J(PG:2)
	at amnh.ba(PG:287)
	at mfr.aE(PG:30)
	at mfr.ax(PG:2)
	at kvv.run(PG:962)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Module installation works fine, but many apps no longer work correctly for seemingly no reason (banking apps are "not authorized for this device", Steam can't use my camera, etc) due to this issue as well. Trying to grant the permission manually with pm results in `MANAGE_USERS` being rejected for being "unalterable" and `CREATE_USERS` not being requested by the app.

**Comment by nift4** [comment]
Is Play Store a system app? Or are you perhaps affected by #171
