### ISSUE TITLE
Rooted Android 12 Stock - Magisk module install fails installing GmsCore

### ISSUE THREAD

**Issue by ethanhall** [nift4/microg_installer_revived#48]
Spoofing is not working, and whew-inc/FakeGApps 2.0 LSposed module fails with "Failed to find provider com.google.android.gsf.gservices".

I have wiped and flashed clean ROM a few times.  Using root explorer, deleted the following apps before install:

GmsCore
GoogleFeedback
GoogleOneTimeInitializer
GooglePartnerSetup
GoogleServicesFramework
Phonesky
SetupWizard
Velvet

Magisk log:

- Copying zip to temp directory
- Installing microG_Installer_Revived.zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
**************************
 microG Installer Revived 
 by nift4 
**************************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: CHANGELOG
  inflating: customize.sh
  inflating: module.prop
  inflating: README.md
   creating: system/
   creating: system/etc/
   creating: system/etc/permissions/
  inflating: system/etc/permissions/privapp-permissions-org.microG.xml
  inflating: system/etc/permissions/com.google.android.maps.xml
   creating: system/etc/sysconfig/
  inflating: system/etc/sysconfig/org.microG.xml
   creating: system/etc/default-permissions/
  inflating: system/etc/default-permissions/permissions-com.google.android.gms.xml
   creating: system/priv-app/
   creating: system/priv-app/GsfProxy/
  inflating: system/priv-app/GsfProxy/GsfProxy.apk
   creating: system/priv-app/Phonesky/
  inflating: system/priv-app/Phonesky/Phonesky.apk
   creating: system/priv-app/GmsCore/
  inflating: system/priv-app/GmsCore/GmsCore.apk
   creating: system/framework/
  inflating: system/framework/com.google.android.maps.jar
- Installing microG GmsCore
Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification Result]
- Real Play Store not found, installing Fake Store
Success
- Done

LSposed modules log:

----part 1 start----
[ 2022-06-29T02:14:47.290 1000: 5886: 5886 I/LSPosed-Bridge ] Loading module com.thermatk.android.xf.fakegapps from /data/app/~~od7MGKqHUs3p9tBHxjYWYw==/com.thermatk.android.xf.fakegapps-MpRAxW76Em7nfr-688U2Sg==/base.apk
[ 2022-06-29T02:14:47.294 1000: 5886: 5886 I/LSPosed-Bridge ] Loading class com.thermatk.android.xf.fakegapps.FakeSignatures
[ 2022-06-29T02:14:57.255 10318: 7361: 7361 I/LSPosed-Bridge ] Loading module com.thermatk.android.xf.fakegapps from /data/app/~~od7MGKqHUs3p9tBHxjYWYw==/com.thermatk.android.xf.fakegapps-MpRAxW76Em7nfr-688U2Sg==/base.apk
[ 2022-06-29T02:14:57.257 10318: 7361: 7361 I/LSPosed-Bridge ] Loading class com.thermatk.android.xf.fakegapps.FakeSignatures
[ 2022-06-29T02:14:57.397 10318: 7361: 7361 I/LSPosed-Bridge ] Crash unexpectedly: java.lang.RuntimeException: Unable to instantiate application co.g.App package com.google.android.gms: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
at android.app.LoadedApk.makeApplication(LoadedApk.java:1464)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7458)
at android.app.ActivityThread.access$1700(ActivityThread.java:310)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
at android.os.Parcel.createException(Parcel.java:2421)
at android.os.Parcel.readException(Parcel.java:2404)
at android.os.Parcel.readException(Parcel.java:2346)
at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:1256)
at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2679)
at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2667)
at bogh.k(:com.google.android.gms@222116044@22.21.16 (190400-454906765):2)
at bogh.g(:com.google.android.gms@222116044@22.21.16 (190400-454906765):2)
at vzh.attachBaseContext(:com.google.android.gms@222116044@22.21.16 (190400-454906765):17)
at android.app.Application.attach(Application.java:350)
at android.app.Instrumentation.newApplication(Instrumentation.java:1178)
at android.app.LoadedApk.makeApplication(LoadedApk.java:1456)
... 10 more
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.content.ContentService.registerContentObserver(ContentService.java:411)
at android.content.IContentService$Stub.onTransact(IContentService.java:492)
at android.os.Binder.execTransactInternal(Binder.java:1215)
at android.os.Binder.execTransact(Binder.java:1179)

**Comment by nift4** [comment]
After deleting folders and before installing the module, you need to explicitly uninstall (updates) of the apps you deleted. App updates are stored in /data/ and persist deleting the system folder, which causes the broken state you discovered. This in fact is unrelated to this module. :)
Let me know if it now works for you

**Comment by ethanhall** [comment]
> After deleting folders and before installing the module, you need to explicitly uninstall (updates) of the apps you deleted. App updates are stored in /data/ and persist deleting the system folder, which causes the broken state you discovered. This in fact is unrelated to this module. :) Let me know if it now works for you

Oh, wow.  If that fixes this, I'll be thrilled!  So are you saying to delete these additional update files outright, or use the app properties in settings to uninstall updates first before deleting?

**Comment by nift4** [comment]
*You were supposed to use the Android Settings UI to uninstall updates, it has a button for that (although sometimes hidden). Normal uninstall is good as well if that is possible.
