### ISSUE TITLE
Installing modules leads to crashes of many applications

### ISSUE THREAD

**Issue by Yannik** [nift4/microg_installer_revived#6]
After installing the module, a load of apps I got installed are crashing.

Here's the logcat produced by  spotify for example:
```
04-18 22:45:55.129  1563  2135 W ActivityManager: Permission Denial: Accessing service com.google.android.gms/org.microg.gms.gcm.PushRegisterService from pid=9307, uid=10083 requires com.google.android.c2dm.permission.RECEIVE
04-18 22:45:55.129  9307  9337 E AndroidRuntime: FATAL EXCEPTION: firebase-iid-executor
04-18 22:45:55.129  9307  9337 E AndroidRuntime: Process: com.spotify.music, PID: 9307
04-18 22:45:55.129  9307  9337 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
04-18 22:45:55.129  9307  9337 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1740)
04-18 22:45:55.129  9307  9337 E AndroidRuntime: 	at android.app.ContextImpl.bindService(ContextImpl.java:1650)
04-18 22:45:55.129  9307  9337 E AndroidRuntime: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
04-18 22:45:55.129  9307  9337 E AndroidRuntime: 	at cbx.a(SourceFile:22)
04-18 22:45:55.129  9307  9337 E AndroidRuntime: 	at cbx.b(SourceFile:24)
04-18 22:45:55.129  9307  9337 E AndroidRuntime: 	at dys.a(SourceFile:17)
04-18 22:45:55.129  9307  9337 E AndroidRuntime: 	at dyr.a(SourceFile:16)
04-18 22:45:55.129  9307  9337 E AndroidRuntime: 	at dxi.a(SourceFile:1013)
04-18 22:45:55.129  9307  9337 E AndroidRuntime: 	at dyk.run(SourceFile:1078)
04-18 22:45:55.129  9307  9337 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-18 22:45:55.129  9307  9337 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-18 22:45:55.129  9307  9337 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)

```

swiftkey:
```
04-18 22:55:07.071  1563  2011 W ActivityManager: Permission Denial: Accessing service com.google.android.gms/org.microg.gms.gcm.PushRegisterService from pid=15010, uid=10135 requires com.google.android.c2dm.permission.RECEIVE
04-18 22:55:07.072 15010 15061 E AndroidRuntime: FATAL EXCEPTION: firebase-iid-executor
04-18 22:55:07.072 15010 15061 E AndroidRuntime: Process: com.touchtype.swiftkey, PID: 15010
04-18 22:55:07.072 15010 15061 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1740)
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at android.app.ContextImpl.bindService(ContextImpl.java:1650)
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at ig0.b(s:8)
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at ig0.a(s:7)
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at d01.a(s:19)
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at b01.a(s:7)
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at s01.a(s:61)
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at p11.a(s:31)
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at q11.run(Unknown Source:6)
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-18 22:55:07.072 15010 15061 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)

```

I have gone through microg settings to accept permissions and check that signature spoofing is enabled correctly. I've also rebooted since.

The same apps were working perfectly with LOS16 and microg, and LOS17.1 without micro installed.

**Comment by Yannik** [comment]
Can confirm that neither removing app cache, app data or reinstalled affected apps fixes this. Unfortunately a large number of apps are affected, presumably all that have some google cloud messaging capability. I've played with enabling/disabling microg gcm without being able to fix it that way either.

**Comment by Yannik** [comment]
![Screenshot_20200418-230103_microG_Services_Core](https://user-images.githubusercontent.com/801996/79671161-83a08980-81c8-11ea-88e4-c882db2977db.png)

**Comment by nift4** [comment]
Reinstalling all apps should do it, it's not caused by the module but because dirty-installing microG. You can leave this open anyway, I'll help you.

**Comment by nift4** [comment]
Okay, 
- Go to microG settings and enable GCM
- Dial *#*#​CHECKIN#*#*
- Reinstall one of the apps without restoring data backup before having them started at least once

**Comment by Yannik** [comment]
@nift4 Actually, you're right. Installing the apps over the current installation (no need for reinstall, simply install over the current installed apk) fixes this.

When I did testing re-installation earlier, I used apk extracter to save the apks, which apparantly did not extract some native libs and therefore lead to the crash after reinstallation. 

Thank you!

**Comment by Yannik** [comment]
@nift4 The reason that my re-installation failed, that the APK i selected is a "split apk". My old apk extracter only extracted the base.apk which lead to the app crashing after re-install.
