### ISSUE TITLE
INSTALL_FAILED_VERSION_DOWNGRADE

### ISSUE THREAD

**Issue by fusionneur** [nift4/microg_installer_revived#88]
android 12 oxygenos oneplus 7t pro

```

- Copying zip to temp directory
- Installing mG-no-Volla.zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
**************************
 microG Installer Revived 
 by nift4 
**************************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: androidacy-config.json
  inflating: CHANGELOG
  inflating: customize.sh
  inflating: LICENSE
  inflating: module.prop
  inflating: README.md
   creating: system/
   creating: system/etc/
   creating: system/etc/default-permissions/
  inflating: system/etc/default-permissions/permissions-com.google.android.gms.xml
   creating: system/etc/permissions/
  inflating: system/etc/permissions/com.google.android.maps.xml
  inflating: system/etc/permissions/privapp-permissions-org.microG.xml
   creating: system/etc/sysconfig/
  inflating: system/etc/sysconfig/org.microG.xml
   creating: system/framework/
  inflating: system/framework/com.google.android.maps.jar
   creating: system/priv-app/
   creating: system/priv-app/GmsCore/
  inflating: system/priv-app/GmsCore/GmsCore.apk
   creating: system/priv-app/GsfProxy/
  inflating: system/priv-app/GsfProxy/GsfProxy.apk
   creating: system/priv-app/Phonesky/
  inflating: system/priv-app/Phonesky/Phonesky.apk
   creating: system/product/
   creating: system/product/overlay/
   creating: system/product/overlay/microGOverlay/
  inflating: system/product/overlay/microGOverlay/microGOverlay.apk
  inflating: uninstall.sh
- Real Play Store not found, using Fake Store
- Installing microG GmsCore
Success: streamed 79623566 bytes
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.google.android.gms signatures do not match previously installed version; ignoring!]
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.google.android.gms signatures do not match previously installed version; ignoring!]
- Real Play Store not found, installing Fake Store
Success: streamed 78431 bytes
Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification Result]

Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Error: Failed to parse APK file: : Failed to parse 
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:587)
	at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1357)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1316)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25948)
	at android.os.Binder.shellCommand(Binder.java:970)
	at android.os.Binder.onTransact(Binder.java:854)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8987)
	at android.os.Binder.execTransactInternal(Binder.java:1226)
	at android.os.Binder.execTransact(Binder.java:1163)
Caused by: java.io.IOException: Failed to load asset path  from fd 1005
	at android.content.res.ApkAssets.nativeLoadFd(Native Method)
	at android.content.res.ApkAssets.<init>(ApkAssets.java:306)
	at android.content.res.ApkAssets.loadFromFd(ApkAssets.java:177)
	at android.content.pm.parsing.ApkLiteParseUtils.parseApkLiteInner(ApkLiteParseUtils.java:295)
	at android.content.pm.parsing.ApkLiteParseUtils.parseApkLite(ApkLiteParseUtils.java:283)
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:581)
	... 12 more
- Done


```

**Comment by nift4** [comment]
as i said in readme, have to properly uninstall gapps first. cannot install over gapps

**Comment by nift4** [comment]
improper way, need to delete apk files

**Comment by nift4** [comment]
hmm, i dont think so, but basically, you edit system, product, system_ext partitions to remove all google app apks

**Comment by nift4** [comment]
if you uninstalled it with pm cli and deleted apk from filesystem then its not cached
